# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-10 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv',
            old_name='released_date',
            new_name='release_date',
        ),
    ]
