# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0002_auto_20191110_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='release_date',
            field=models.DateField(blank=True),
        ),
    ]
