# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0004_auto_20191111_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tv',
            name='release_date',
            field=models.DateField(),
        ),
    ]
